### ISSUE TITLE
is he dead jim?

### ISSUE THREAD

**Issue by AiyionPrime** [torsten-schenk/ledbadge#1]
Have gotten any insights in about how to properly flash the device under linux?

**Comment by torsten-schenk** [comment]
Actually yes, I just wonder, why the project is empty - obviously I didn't commit the code yet ;) I will search the code on my harddrive and commit it.

**Comment by AiyionPrime** [comment]
While organizing my desk a few days ago I came across the badge again. Any chance the said harddrive is still available? :D

**Comment by AiyionPrime** [comment]
What a shame; I missed the code has been here for quite a while now. I'll look into it in advent, thank you!
